name: groceryapp
description: An online grocery shopping application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  map: ^0.1.0+1
  latlng: ^0.0.2
  gps: ^0.1.1
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  persistent_bottom_nav_bar: ^2.0.5
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - images/

  fonts:
    - family:  Custom_icons_iconsdart
      fonts:
        - asset: fonts/Custom_icons_iconsdart.ttf


    - family:  Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
